### ISSUE TITLE
Create foresight DNS zones and delegation

### ISSUE THREAD

**Issue by lucbelliveau** [PHACDataHub/foresight#28]
- [x] Create a DNS zone for foresight.phac.alpha.canada.ca in the GCP project
- [x] Create a DNS zone for serum.aspc.alpha.ca in the GCP project
- [x] Submit a PR using https://github.com/PHACDataHub/dns for delegation

**Comment by simardeep1792** [comment]
@lucbelliveau 

 It is my understanding that "Serum" serves as the French translation for "Foresight." Given this, would it not be more appropriate for the DNS zone to be unified under a single domain, such as foresight-serum.phac-aspc.alpha.canada.ca?Could you please confirm whether these domains are associated with the same project or if they represent distinct initiatives?
